using Content.Client._ES.Masks;
using Content.Client._ES.Objectives;
using Content.Client._ES.Objectives.Ui;
using Content.Client.Message;
using Content.Client.Mind;
using Content.Client.Roles;
using Content.Client.UserInterface.Controls;
using Content.Shared._ES.Auditions.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._ES.Mind.Ui;

[GenerateTypedNameReferences]
public sealed partial class ESCharacterWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _ent = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly JobSystem _job;
    private readonly ESMaskSystem _mask;
    private readonly MindSystem _mind;
    private readonly ESObjectiveSystem _objective;

    public ESCharacterWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _job = _ent.System<JobSystem>();
        _mask = _ent.System<ESMaskSystem>();
        _mind = _ent.System<MindSystem>();
        _objective = _ent.System<ESObjectiveSystem>();

        Update();
    }

    public void Update()
    {
        // Oh no!
        if (_player.LocalEntity is not { } localEntity)
            return;

        SelfView.SetEntity(localEntity);

        if (!_mind.TryGetMind(localEntity, out var mind, out var mindComp))
            return;

        if (_ent.TryGetComponent<ESCharacterComponent>(mind, out var character))
            NameLabel.SetMarkup(Loc.GetString("es-character-window-name-fmt", ("name", character.Name)));

        if (_mask.TryGetMask((mind, mindComp), out var maskId))
        {
            if (_job.MindTryGetJob(mind, out var job))
            {
                JobLabel.SetMarkup(Loc.GetString("es-character-window-job-fmt", ("name", job.LocalizedName)));
            }

            var mask = _prototype.Index(maskId);
            var troupe = _prototype.Index(mask.Troupe);
            MaskLabel.SetMarkup(Loc.GetString("es-character-window-mask-fmt",
                ("name", Loc.GetString(mask.Name)),
                ("color", mask.Color)));
            TroupeLabel.SetMarkup(Loc.GetString("es-character-window-troupe-fmt",
                ("name", Loc.GetString(troupe.Name)),
                ("color", troupe.Color)));
        }

        var info = _mask.GetCharacterInfoBlurb((mind, mindComp));
        var formattedMsg = new FormattedMessage();
        foreach (var msg in info)
        {
            formattedMsg.AddMessage(msg);
            formattedMsg.PushNewline();
        }
        InfoBlurbText.SetMessage(formattedMsg);
        InfoBlurbText.Visible = !formattedMsg.IsEmpty;

        ObjectivesContainer.Children.Clear();
        foreach (var objective in _objective.GetObjectives(mind))
        {
            var control = new ESObjectiveControl();
            control.SetObjective(objective);
            ObjectivesContainer.AddChild(control);
        }
    }
}
